### ISSUE TITLE
Complete CSIT-Programming-with-Python

### ISSUE THREAD

**Issue by karsterr** [karsterr/CSIT#17]
Write the solutions of exercises

**Comment by angrezichatterbox** [comment]
Sorry I had some issues earlier could I do this .. Where can I find the pdf exactly for solving this work and what should be the formatting for the solution

**Comment by karsterr** [comment]
> Sorry I had some issues earlier could I do this .. Where can I find the pdf exactly for solving this work and what should be the formatting for the solution

All required info you need is included in repository. PDF and example file formats are available there

**Comment by karsterr** [comment]
I forgot to mention that this issue will be close when all issues closed in this repo.
