### ISSUE TITLE
Solve exercises of Working with Text

### ISSUE THREAD

**Issue by karsterr** [karsterr/CSIT#3]
Write the solutions of exercises

**Comment by angrezichatterbox** [comment]
Could u assign me to do this I would write the solutions for this Chapter

**Comment by angrezichatterbox** [comment]
I have written the solutions for this exercise Please Check it and I would love to make changes if necessary ... 😊

**Comment by karsterr** [comment]
@angrezichatterbox Sorry for my late return. I've been busy with my exams. These are finally over and I'm back right now. If I remember correct, I merged your PR. If I didn't, I'll make sure check it out. Then I'll close the issue after I'm done making documentation of it.
