### ISSUE TITLE
Solve exercises of Making Choices

### ISSUE THREAD

**Issue by karsterr** [karsterr/CSIT#4]
Write the solutions of exercises

**Comment by Jainil2004** [comment]
hello @karsterr, i am interested in solving this issue and would love to help. could you please assign me this issue?

**Comment by karsterr** [comment]
> hello @karsterr, i am interested in solving this issue and would love to help. could you please assign me this issue?

All set.

**Comment by Jainil2004** [comment]
hi @karsterr, so I was traveling for the past two days, and hence was not able to solve the issue, but I'll start working on the issue on priority basis today itself. I hope you understand.
Thank you

**Comment by karsterr** [comment]
@Jainil2004 no need to rush. If you check project CSIT, I planned this issues solve date next month. So, take your time :)

**Comment by Jainil2004** [comment]
hi @karsterr, I've solved the specific issue and have submitted a PR. Please have a look and do let me know if there is a need to make modifications. I'll be very happy to help 
Thank you

**Comment by karsterr** [comment]
@Jainil2004 I reviewed your commits caught minor issues in it. I commented them in your PR. Please check them when you are available.

**Comment by Jainil2004** [comment]
@karsterr thank you for the review and I apologize for the minor issues it had. I have checked the minor issues in the code and I am currently working on the fix. Please allow me some time and I'll get back to you with the updated PR soon.
Thank you

**Comment by Jainil2004** [comment]
@karsterr, I have addressed all the issues you reported in the updated PR.  Thank you for your valuable time. Please have a look on the improved PR and do let me know if you find anything out of place.
Thank you

**Comment by karsterr** [comment]
@Jainil2004 Sorry for my late return. I was busy with my exams like I mentioned before. I'm back now. I merged your PR and I'll close the issue when I done with documentation. Thanks for your patience.

**Comment by Jainil2004** [comment]
@karsterr  no problem at all. And thanks for reviewing the PR :)
