### ISSUE TITLE
Solve exercises of A Modular Approach to Program Organization

### ISSUE THREAD

**Issue by karsterr** [karsterr/CSIT#5]
Write the solutions of exercises

**Comment by Jainil2004** [comment]
@karsterr no worries and thank you for assigning me the issue. I will update you once I am done with the solution for this issue. Also all the very best for your exams 👍
thank you

**Comment by Jainil2004** [comment]
hi @karsterr, I have successfully resolved the issue and have created a PR for the same. Please review it and do let me know if there are some errors or problem. I'll be happy to help
Thank you

**Comment by Jainil2004** [comment]
@karsterr any updates for me?

**Comment by karsterr** [comment]
@Jainil2004, I explained my current situation on the latest comment on Issue number 4. Same goes on this issue. Sorry again to make you wait this long.

**Comment by Jainil2004** [comment]
@karsterr no worries here as well. thanks for reviewing the PR :)
